ENV['PATH'] = ENV['PATH'] + ';C:\BitNami\redmine-2.5.1-1/git/bin'
ENV['PATH'] = ENV['PATH'] + ';C:\BitNami\redmine-2.5.1-1/subversion/bin'
ENV['PATH'] = ENV['PATH'] + ';C:\BitNami\redmine-2.5.1-1\imagemagick'
ENV['MAGICK_CODER_MODULE_PATH'] = 'C:\BitNami\REDMIN~1.1-1\IMAGEM~1\modules\coders'
ENV['PATH'] = ENV['PATH'] + ';C:\BitNami\redmine-2.5.1-1\ruby\bin'
